#!/bin/sh

# Package
#PACKAGE="mods"
# Others
#INSTALL_DIR="/usr/local/${PACKAGE}"

#start()
#{
#su -c "mv ${INSTALL_DIR}/.app/ ${INSTALL_DIR}/app/"
#}

#stop()
#{
#su -c "mv ${INSTALL_DIR}/app/ ${INSTALL_DIR}/.app/"
#}
LOG=/var/log/StorJ
case $1 in
  start)
    echo `date` "StorJ Storagenode is installed properly & started" >> $LOG
    exit 0
    ;;
  stop)
    echo `date` "StorJ Storagenode is stopped" >> $LOG
    docker stop storagenode
    docker rm -f storagenode
    exit 0
    ;;
  status)
    exit 0
    ;;
  log)
    echo $LOG
    exit 0
    ;;
esac

#case $1 in
#	start)
#		start
#		exit 0
#	;;
#	stop)
#		stop
#		exit 0
#	;;
#	status)
#		exit 0
#	;;
#	log)
#		exit 0
#	;;
#esac

#exit 0